version: '3.1'
# this is a testing docker-compose. This is not really what's sent to production
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - unix_socket:/var/run/postgresql
    environment:
      ROCKET_ENV: production
    env_file:
      - .env
    ports:
      - 8000:8000

  db:
    image: postgres
    restart: always
    volumes:
      - unix_socket:/var/run/postgresql
      - ./sql/init_script.sql:/docker-entrypoint-initdb.d/init_script.sql
    environment:
      POSTGRES_DB: wanderways_db
      POSTGRES_USER: wanderways_api
      POSTGRES_PASSWORD: pwd
volumes:
  unix_socket: